version: '2'
services:
  server:
    container_name: frontend
    build: .
    command: yarn dev
    ports:
      - "3000:3000"
    expose:
      - 8080
    environment:
      - PORT=3000
    networks:
      - banking
networks:
  banking:
    name: bank-network
    external: true