version: '2'
services:
  server1:
    container_name: frontend
    build: ./frontend
    command: yarn run dev
    ports:
      - "3000:3000"
    expose:
      - 8080
    environment:
      - PORT=3000
  server2:
    container_name: backend
    build: ./backend/
    command: yarn start
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      - PORT=8080
      - DEBUG=backend:server